name: Deploy MuleSoft Application Demo
on:
  push:
    branches:
      - feature-branch
 
jobs:
  call-workflow:
    uses: IndrajithKatta07/pipeline/.github/workflows/pipeline.yml@main
    secrets: inherit
